version: '3'

networks:
  e-commerce:
    driver: 'bridge'

services:
  e-commerce:
    build:
      context: docker/app
    ports:
      - ${APP_PORT}:80
      - "9001:9001"
    volumes:
      - ${APP_PATH}:/var/www/html
      - ./docker/app/logs/nginx:/var/log/nginx
      - ./docker/app/.composer:/root/.composer
      - ./docker/app/resolv.conf:/etc/resolv.conf
    #      - ./docker/docker-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - mysql
    networks:
      - e-commerce

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33067:3306
    volumes:
      - ./mysql/mysql-2:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - e-commerce
  # mailpit:
  #   image: "axllent/mailpit:latest"
  #   container_name: mailpit
  #   restart: always
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   networks:
  #     - e-commerce
